import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
// import LoadModule from "./module/LoadModule.js";
import LoadMoreModule from "./module/LoadMoreModule.js";
// import SelectCusModule from "./module/SelectCusModule.js";
import CheckModule from "./module/CheckModule.js";
import Select2Module from "./module/Select2Module.js";
// import LetterModule from "./module/LetterModule.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
// import IsotopeModule from "./module/IsotopeModule.js";
import HeaderModule from "./module/HeaderModule.js";
import PlusMinusModule from "./module/PlusMinusModule.js";
import SideModule from "./module/SideModule.js";
import ShowHideModule from "./module/ShowHideModule.js";
// import OpenPopup from "./module/OpenPopup.js";
import ScrollReveals from "./module/ScrollReveals.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import Animated from "./module/Animated.js";
import CollapseModule from "./module/CollapseModule.js";
// import CmtModule from "./module/CmtModule.js";
import scrollContent from "./module/ScrollContent.js";
// import ShowImgModule from "./module/ShowImgModule.js";
import TextAniModule from "./module/TextAniModule.js";
import ParallaxModule from "./module/ParallaxModule.js";
import CountUpModule from "./module/CountUpModule.js";
import FormModule from "./module/FormModule.js";
import CopyModule from "./module/CopyModule.js";
import FileModule from "./module/FileModule.js";
import UploadFileProgressModule from "./module/UploadFileProgressModule.js";
import TimerModule from "./module/TimerModule.js";
import ScrollDesktop from "./module/ScrollDesktop.js";
import PhuocModule from "./module/Phuoc.js";
// import SelectIsotope from "./module/SelectIsotope.js";


window.addEventListener("DOMContentLoaded", () => {
    MobileModule();
    AosModule();
    BtnToTopModule();
    PopupModule();
    SwiperModule();
    // LoadModule();
    // SelectCusModule();
    CheckModule();
    // SearchModule();
    Select2Module();
    // LetterModule();
    GalleryModule();
    TabModule();
    // IsotopeModule();
    HeaderModule();
    PlusMinusModule();
    SideModule();
    ShowHideModule();
    // OpenPopup();
    ScrollReveals();
    Animated();
    SmoothScrollModule();
    LoadMoreModule();
    CollapseModule();
    // CmtModule();
    scrollContent();
    // ShowImgModule();
    TextAniModule();
    ParallaxModule();
    CountUpModule();
    FormModule();
    CopyModule();
    FileModule();
    UploadFileProgressModule();
    // SelectIsotope();
    TimerModule();
    ScrollDesktop();
    PhuocModule();
});